stages:
    - deploy

deploy:
    stage: deploy
    script:
        ##
        ## Install ssh-agent if not already installed, it is required by Docker.
        ##
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"

        ##
        ## Install rsync if not already installed
        ##
        - "which rsync || ( apt-get update -y && apt-get install rsync -y )"

        ##
        ## Run ssh-agent (inside the build environment)
        ##
        - eval $(ssh-agent -s)

        ##
        ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
        ## We're using tr to fix line endings which makes ed25519 keys work
        ## without extra base64 encoding.
        ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
        ##
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

        ##
        ## Create the SSH directory and give it the right permissions
        ##
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        ##
        ## Scan the keys of the server.
        ##
        - ssh-keyscan pyxxilated.studio >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts

        ##
        ## Deploy to gitlab and to the server
        ##
        - rsync -hrvz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" personalsite static requirements.txt gitlab@pyxxilated.studio:/var/www/pyxxilated.studio/
    environment:
        name: staging
        url: https://www.pyxxilated.studio
    only:
        - master
    except:
        changes:
            - "*.md"
